interpretation_task:
  description: >
    Evaluate the user's request and determine the required action:
    - Adding a field: Identify where the field is currently available (if provided),
      determine how to propagate it through necessary models or transformations,
      and assess the impact on related models and dependencies.
    - Modifying an existing model: Identify specific changes needed, evaluate the
      impact on structure, relationships, and downstream dependencies.
    - Retrieving specific information: Identify models containing relevant data,
      analyze relationships, and determine queries or transformations needed.

    Reflect on the request to generate a concise plan for the approach and provide
    a clear summary of the required action and its implications.

  expected_output: >
    Return one of the following actions:
    - ADD_COLUMN
    - MODIFY_MODEL
    - RETRIVE_INFO

    Additionally, include a short explanation of the work required for the action.
    The output should be minimal and focused, avoiding extra commentary or filler text.

evaluation_task:
  description: >
    Evaluate the interpretation of the user request and determine the necessary steps to handle it effectively. 
    Include only relevant considerations based on the following topics:
    - Target models or files
    - Field existence
    - Documentation needs
    - Dependencies and relationships
    - Performance/design considerations
    - Tests
    - dbt project config
    - Code or logic generation
    
    Possible actions and considerations may include:
    - Identifying the target models or files affected by the request.
    - Analyzing upstream and downstream dependencies to locate the change points.
    - Assessing the need for adjustments in documentation, tests, or configuration files.
    - Evaluating performance impacts and ensuring maintainability.
    - Generating necessary SQL logic fragments (e.g., CTEs, columns).
    - Determining if an intermediate model is required for the changes.
    - Highlighting potential granularity changes or unique key impacts.

  expected_output: >
    A concise summary of the high-level tasks required to fulfill the request.
    If additional context (e.g., project structure or lineage) is needed, clearly
    state this and provide only reflections based on the given information.

    Avoid filler text or unnecessary explanations, and focus exclusively on actionable insights.